[package]
name = "secrets-app"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
dotenvy = "0.15"
glob = "0.3"
inquire = "0.7"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
